# Generated by Django 4.1.5 on 2023-04-05 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0002_remove_authors_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='libra.categories'),
        ),
    ]
